#!/bin/bash

set -euxo pipefail

cd /work

build_type="$(cat /opt/ssh-local-exec/build-type)"

touch /opt/ssh-local-exec/env

case "${build_type}" in
debug)
    cargo build
    ;;
coverage)
    cargo llvm-cov show-env --export-prefix >/opt/ssh-local-exec/env
    . /opt/ssh-local-exec/env
    cargo build
    ;;
*)
    echo "unknown build-type: ${build_type}" >&2
    exit 1
    ;;
esac
