#!/bin/bash

set -euxo pipefail

cd /work

build_type="$(cat /opt/ssh-local-exec/build-type)"

. /opt/ssh-local-exec/env

case "${build_type}" in
debug) ;;
coverage)
    mkdir /work/target/lcov
    cargo llvm-cov report --lcov >/work/target/lcov/lcov.info
    ;;
*)
    echo "unknown build-type: ${build_type}" >&2
    exit 1
    ;;
esac
